name: Deploy to RaphaelL2e.github.io

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tech-blog
        uses: actions/checkout@v4
        
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.115.4'
          extended: true
          
      - name: Build
        run: hugo --gc --minify --baseURL "https://raphaell2e.github.io/"
        
      - name: Deploy to RaphaelL2e.github.io
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          external_repository: RaphaelL2e/RaphaelL2e.github.io
          publish_branch: main
          publish_dir: ./public
